apiVersion: v1
kind: Namespace
metadata:
  name: server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server
  namespace: server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: server
  namespace: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccount: server
      containers:
      - name: app
        image: test/sa-identity-server
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: 768M
          limits:
            cpu: 500m
            memory: 768M
---
apiVersion: v1
kind: Service
metadata:
  name: app 
  namespace: server
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080

