apiVersion: v1
kind: Namespace
metadata:
  name: client
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client
  namespace: client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      serviceAccount: client
      volumes:
        - name: client-token
          projected:
            sources:
            - serviceAccountToken:
                path: client-token
                expirationSeconds: 600
                audience: server
      containers:
      - name: app
        image: test/sa-identity-client
        imagePullPolicy: Never
        env:
        - name: SERVER_CONNSTRING
          value: "http://app.server:8081"
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /var/run/secrets/tokens
            name: client-token
        resources:
          requests:
            cpu: 500m
            memory: 768M
          limits:
            cpu: 500m
            memory: 768M
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: client
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - port: 8080
      targetPort: 8080
